# Generated by Django 2.2.9 on 2022-04-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220408_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Lighting', 'Lighting'), ('Walls & Floor', 'Walls & Floor'), ('Furnishing', 'Furnishing')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_sub_category',
            field=models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta'), ('Gama', 'Gama'), ('delta', 'delta')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Carpet', 'Carpet'), ('Wellness', 'Wellness'), ('Kitchen', 'Kitchen'), ('Lighting', 'Lighting'), ('Bath', 'Bath')], default=None, max_length=30),
        ),
    ]
