# Generated by Django 2.2.9 on 2022-04-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220408_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Walls & Floor', 'Walls & Floor'), ('Furnishing', 'Furnishing'), ('Lighting', 'Lighting')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_sub_category',
            field=models.CharField(choices=[('Gama', 'Gama'), ('delta', 'delta'), ('alpha', 'alpha'), ('beta', 'beta')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Wellness', 'Wellness'), ('Carpet', 'Carpet'), ('Kitchen', 'Kitchen'), ('Bath', 'Bath'), ('Lighting', 'Lighting')], default=None, max_length=30),
        ),
    ]
